# Generated by Django 4.1.7 on 2023-03-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('DeptoId', models.IntegerField(primary_key=True, serialize=False)),
                ('DeptoNombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('puestoId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('puestoNombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('TipoEmpId', models.IntegerField(primary_key=True, serialize=False)),
                ('TipoEmpNombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('correo', models.EmailField(max_length=254)),
                ('DepartamentoId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rrhh.departamentos')),
                ('TipoEmpleado', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.tipoempleado')),
                ('puestoId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rrhh.puestos')),
            ],
        ),
    ]
